CET/CET/urls.py
from django.contrib import admin
from django.urls import path , re_path
from django.conf.urls import include
from manager import views as mngr_views
from reg import views as reg_views
# urlpatterns = [
#     path("admin/", admin.site.urls),
#     re_path(r"^$", mngr_views.hello),
#     path('test/', mngr_views.show_items, name='test'),
# ]
urlpatterns = [
    re_path(r"^admin\/?", admin.site.urls),
    re_path(r"^$", mngr_views.hello), # 支持正则表达式

    # 下面为路由分发, 请各个模块按自己的前缀, 在自己的模块内的urls.py编写url路径
    path("manager/", include("manager.urls",namespace="manager")),
    path("exam/", include("exam.urls")),
    path("reg/", include("reg.urls")),
    path("marking/", include("marking.urls")),
    path("user/", include("user.urls")),
]

CET/user/urls.py
from django.urls import path, re_path
# 从自己的 app 目录引入 views
from user import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

app_name = 'user'
urlpatterns = [
    # 初始界面，选择谁登录

    # 用正则表达式设置，默认界面和index都可以登录
    re_path(r'^$|index', views.index, name='index'),

    path('log', views.log, name='log'),

    path('tea_signin', views.tea_signin, name='tea_signin'),
    path('stu_signin', views.stu_signin, name='stu_signin'),
    path('tea_signup', views.tea_signup, name='tea_signup'),
    path('stu_signup', views.stu_signup, name='stu_signup'),
    path('logout', views.logout, name='logout'),
    path('stu_all', views.stu_all, name='stu_all'),
    path('stu_info', views.stu_info, name='stu_info'),
    path('mod_info_stu', views.mod_info_stu, name='mod_info_stu'),
    path('go_to_exam', views.go_to_exam, name='go_to_exam'),
    path('go_to_mark', views.go_to_mark, name='go_to_mark'),
    path('stu_exam_grade', views.get_stu_exam_grade, name='stu_exam_grade'),
    path('tea_info', views.tea_info, name='tea_info'),
    path('logout_tea', views.logout, name='logout_tea'),
    path('mod_info_tea', views.mod_info_tea, name='mod_info_tea'),
    path('mod_password_stu', views.mod_password_stu, name='mod_password_stu'),
    path('mod_password_tea', views.mod_password_tea, name='mod_password_tea'),
    path('sucess_info', views.sucess_info, name='sucess_info'),
    path('captcha_img/',views.captcha_img,name='captcha_img'),
    path('forget_password',views.forget_password,name='forget_password'),
    path('forget_password_tea',views.forget_password_tea,name='forget_password_tea'),
    path('send',views.send_checkcode,name='send'),
    path('modify',views.modify_pwd, name='modify'),
    path('modify_tea',views.modify_pwd_tea, name='modify_tea'),
    path('introduction',views.introduction, name='introduction'),
    path('English_strategy',views.English_strategy, name='English_strategy'),
    path('testinfo',views.testinfo, name='testinfo'),
    path('testtest',views.testtest, name='testtest'),
    path('test.pdf', serve, {'document_root': settings.MEDIA_ROOT, 'path': 'test.pdf'}, name='test-pdf'),
    path('examiee.pdf', serve, {'document_root': settings.MEDIA_ROOT, 'path': 'examiee.pdf'}, name='test-pdf'),
    path('1.pdf', serve, {'document_root': settings.MEDIA_ROOT, 'path': '1.pdf'}, name='test-pdf'),
    path('2.pdf', serve, {'document_root': settings.MEDIA_ROOT, 'path': '2.pdf'}, name='test-pdf')
]

# 配置静态文件URL
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CET/user/models.py
from django.db import models

class Student(models.Model):
    id = models.AutoField(primary_key=True) # 考号
    # self_number = models.IntegerField() # 身份证
    self_number = models.CharField(max_length=18,unique=True,null = False)
    name = models.CharField(max_length=30)
    school = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    phone = models.CharField(max_length=12,unique=True,null=False)
    email = models.CharField(max_length=20)

    class Meta:
        verbose_name = '学生'
        verbose_name_plural = '学生'

    def __str__(self):
        return self.name

class Teacher(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30)
    phone = models.CharField(max_length=12,unique=True,null=False)
    password = models.CharField(max_length=30)

    class Meta:
        verbose_name = '教师'
        verbose_name_plural = '教师'

    def __str__(self):
        return self.name

CET/user/forms.py
from django import forms
from .models import Student
from django.contrib.auth.forms import PasswordChangeForm


class ModifyInfoForm(forms.Form):
    name = forms.CharField(label='姓名', max_length=100, required=False)
    school = forms.CharField(label='学校', max_length=100, required=False)
    phone = forms.CharField(label='电话', max_length=100, required=False)
    email = forms.EmailField(label='邮箱', max_length=100, required=False)

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        school = cleaned_data.get('school')
        phone = cleaned_data.get('phone')
        email = cleaned_data.get('email')

        # 如果字段都为空，则返回原始数据
        if not name and not school and not phone and not email:
            raise forms.ValidationError("请至少填写一个字段")

        return cleaned_data


class ModifyInfoForm_tea(forms.Form):
    name = forms.CharField(label='姓名', max_length=100, required=False)
    phone = forms.CharField(label='电话', max_length=100, required=False)

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        phone = cleaned_data.get('phone')
        # 如果字段都为空，则返回原始数据
        if not name and  not phone :
            raise forms.ValidationError("请至少填写一个字段")

        return cleaned_data


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(label='旧密码', widget=forms.PasswordInput)
    new_password1 = forms.CharField(label='新密码', widget=forms.PasswordInput)
    new_password2 = forms.CharField(label='确认密码', widget=forms.PasswordInput)

CET/user/views.py
import hashlib
import uuid
import time,datetime

from django.contrib.auth.hashers import make_password
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import messages
from user import models
from user.models import Student
from user.models import Teacher
import random
from django.urls import reverse
from django.views.decorators.csrf import csrf_protect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from manager import db_operation as db
from .forms import ModifyInfoForm
from .forms import ModifyInfoForm_tea

from .forms import ChangePasswordForm

from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from common.captcha_4char import captcha
from io import BytesIO
from django.core.mail import send_mail
import requests
'''
初始页面 表单 http://127.0.0.1:8000/user/index 选择登陆谁
学生登陆界面：http://127.0.0.1:8000/user/stu_signin ，输入用户名和密码，正确的话跳转到下一个用户信息页面，不正确的话保持在该页面，但是不知道为啥错误提示不显示
教师登陆页面：http://127.0.0.1:8000/user/tea_signin ， 同样，可以正确判断输入是否符合，但是报错信息不知道为啥不显示
学生注册：http://127.0.0.1:8000/user/stu_signup，可以判断已存在的用户，密码不一致啥的，还是报错信息不会显示
教师注册：http://127.0.0.1:8000/user/tea_signup，同上
忘记密码的逻辑还没写，不知道忘记密码之后，要靠啥验证身份信息
后边的个人信息页面还没写，明天再写
'''
# 5.24.新问题：注册成功后不会跳转到新页面了

# 作品赛添加引用
import secretflow as sf
import spu


# 新增生成验证码功能

def captcha_img(request):
    img,code=captcha.veri_code()
    # 将code保存到session会话中
    request.session['checkcode']=code
    stream = BytesIO()
    img.save(stream,'PNG')
    return HttpResponse(stream.getvalue())


def index(request):
    return render(request,'users/index.html')


def log(request):
    return render(request, 'log/test.html')



#选择是教师登录还是学生登陆,接收请求数据
@csrf_protect
def choose_sign(request):
    if request.method == 'POST':
        login_type = request.POST.get('login_type')
        if login_type == 'student':
            return redirect('user:stu_signin')  # 跳转到学生登录页面的URL名称
            # 跳转过去报错，要设置默认的个人信息吗？
        elif login_type == 'teacher':
            return redirect('user:tea_signin')  # 跳转到教师登录页面的URL名称

    return render(request, 'users/index.html')
#登录

#教师登录

def tea_signin(request):
    if request.method == 'POST':
        id = request.POST.get('account')
        password = request.POST.get('password')
        # 获取表单提交的验证码
        checkcode = request.POST.get('check_code')
        # 获取session会话中的checkcode
        request.session.get('checkcode')
        session_checkcode = request.session.get('checkcode')
        if checkcode and (checkcode.lower() != session_checkcode.lower()):
            # 添加错误信息
            error_message = "验证码填写错误"
            return render(request, 'users/tea_signin.html', {'error_message': '验证码填写错误'})

        tea ,error  = db.user.select_tea_by_phone(id)
        if error == db.NOT_EXIST:
            # 报错信息，用户不存在
            db.sys_log("用户不存在",db.LOG_ERR)
            return render(request,'users/tea_signin.html', {'error_message':'用户不存在'})
        elif tea != None and tea.password == password:
            # 登录成功，跳转到下一个用户信息页面
            db.sys_log("教师登录成功",db.LOG_OK)
            # 会话：记录登陆人
            request.session['user_tea'] = id  # 记录当前用户的身份id
            return redirect('user:tea_info')  # 跳转到用户信息页面的URL名称
        else:
            # 密码错误
            db.sys_log("密码错误",db.LOG_ERR)
            return render(request,'users/tea_signin.html', {'error_message':'密码错误'})

    return render(request,'users/tea_signin.html')


# modified
# here we give a stu dict
stu_dict = {}

#学生登录
def stu_signin(request):
    if request.method == 'POST':
        id = request.POST.get('account')
        password = request.POST.get('password')
        # print(type(id), type(password))
        print(stu_dict)

        # 获取表单提交的验证码
        checkcode=request.POST.get('check_code')
        # 获取session会话中的checkcode
        # request.session.get('checkcode')
        session_checkcode=request.session.get('checkcode')
        if checkcode and (checkcode.lower() != session_checkcode.lower()):
            # 添加错误信息
            error_message = "验证码填写错误"
            return render(request, 'users/stu_signin.html', {'error_message': '验证码填写错误'})

        '''
        stu ,error  = db.user.select_stu_by_phone(id)
        if error == db.NOT_EXIST:
            # 报错信息，用户不存在
            db.sys_log("用户不存在",db.LOG_ERR)
            return render(request,'users/stu_signin.html', {'error_message':'用户不存在'})
        elif stu != None and stu.password == password:
            # 登录成功，跳转到下一个用户信息页面
            db.sys_log("学生登录成功",db.LOG_OK)
            # 会话：记录登陆人
            request.session['user_stu']=id #记录当前用户的身份id
            return redirect('user:stu_all')  # 跳转到用户信息页面的URL名称
        else:
            # 密码错误
            db.sys_log("密码错误",db.LOG_ERR)
            return render(request,'users/stu_signin.html', {'error_message':'密码错误'})
        '''
        if id not in stu_dict:
            # 报错信息，用户不存在
            db.sys_log("用户不存在",db.LOG_ERR)
            return render(request,'users/stu_signin.html', {'error_message':'用户不存在'})
        elif password == stu_dict[id]:
            # 登录成功，跳转到下一个用户信息页面
            db.sys_log("学生登录成功",db.LOG_OK)
            # 会话：记录登陆人
            request.session['user_stu']=id #记录当前用户的身份id
            return redirect('user:stu_all')  # 跳转到用户信息页面的URL名称
        else:
            # 密码错误
            db.sys_log("密码错误",db.LOG_ERR)
            return render(request,'users/stu_signin.html', {'error_message':'密码错误'})
        

    return render(request,'users/stu_signin.html')


#教师注册
def tea_signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        # 检验密码和确认密码是否一致
        if password != confirm_password:
            error_message = '两次输入的密码不一致'
            return render(request, 'users/tea_signup.html', {'error_message': error_message})

        if db.user.insert_tea(username,phone,password)[1] == db.SUCCESS:
            # 注册成功，跳转到用户登录界面
            error_message = None
            # print('数据库添加成功了，下一步应该是重定向到新的界面')
            return redirect('user:tea_signin')  # 跳转到教师登录页面的URL名称

        # 注册失败
        error_message = '注册失败'
        # print('显示注册失败返回到当前页面')
        return render(request, 'users/tea_signup.html', {'error_message': error_message})

    error_message = None
    return render(request, 'users/tea_signup.html')


# 注册成功
def sucess_info(request):
    return render(request, 'users/sucess_info.html')

#学生注册

def stu_signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        id_number = request.POST.get('id_number')
        
        # modified, here we need store the phone and password
        stu_dict[phone] = password

        # 检验密码和确认密码是否一致
        if password != confirm_password:
            error_message = '两次输入的密码不一致'
            return render(request, 'users/stu_signup.html', {'error_message': error_message})

        elif db.user.insert_stu(id_number , username,"",password,phone,"")[1] == db.SUCCESS:
            # 注册成功，跳转到用户登录界面
            # print("user.insert_stu是success")
            return redirect('user:stu_signin')  # 跳转到登录页面的URL名称

        else:
            # 注册失败
            # print(len(id_number))
            # print(type(id_number))
            # # 教师添加成功却显示注册失败
            # print("进入了注册失败的逻辑")
            error_message = '注册失败'
            return render(request, 'users/stu_signup.html', {'error_message': error_message})
            # return redirect('stu_signin')  # 跳转到教师登录页面的URL名称
    return render(request, 'users/stu_signup.html')



# 忘记密码
def forget_password(request):
    if request.method == 'POST':
        phone = request.POST.get('account')
        code = request.POST.get('code')
        # print(phone)
        if request.session.get('phone') == code:
            return render(request,'users/modify_pwd.html',{'phone':phone})

    return render(request, 'users/forget_password.html')

def send_checkcode(request):
    phone = request.GET.get('phone')#这里不知道写的对不对
    # 请求第三方网易云信的服务
    # request ---》》当成浏览器
    url='https://api.netease.im/sms/sendcode.action'
    headers = {}
    headers['Content-Type']='application/x-www-form-urlencoded;charset=utf-8'
    headers['AppKey']='d3ba54c3166e3a9a777de9e37d05146d'
    Nonce = str(uuid.uuid4()).replace('-','')
    headers['Nonce']=Nonce
    CurTime = str(int(time.time()))
    headers['CurTime']= CurTime
    AppSecret='403fcd9614f3'

    CheckSum=hashlib.sha1((AppSecret+Nonce+CurTime).encode('utf-8')).hexdigest()
    headers['CheckSum']= CheckSum
    response=requests.post(url=url,data={'mobile':phone},headers=headers)
    # print(response.text)
    json_result = response.json()
    if json_result.get('code')==200:
        request.session['phone']=json_result.get('obj')  #{'15620528620:'7899'}
        return JsonResponse({'msg':'短信发送成功！'})
    else:
        return JsonResponse({'msg':'短信发送失败！'})


#忘记密码 修改密码
def modify_pwd(request):
    pwd = request.POST.get('new_password1')
    # print(pwd)
    # pwd = '123'
    phone = request.POST.get('phone')
    # print(phone)
    # phone='15620524568'
    # 找到user对象
    student = Student.objects.filter(phone=phone).first()
    # new_password = make_password(pwd)
    student.password = pwd
    # print(student.password)
    student.save()
    # print('密码修改成功')
    messages.success(request, '密码修改成功')
    return render(request, 'users/stu_signin.html', {'success_message': '密码修改成功'})


# 忘记密码--教师端

def forget_password_tea(request):
    if request.method == 'POST':
        phone = request.POST.get('account')
        code = request.POST.get('code')
        # print(phone)
        if request.session.get('phone') == code:

CET/templates/users/forget_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>忘记密码界面</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    <style>
        body {
            background-image: url('{% static "stu_signin_bj.png" %}');
            background-repeat: no-repeat;
            background-size: cover;
        }

        .container {
            margin-top: 100px;
            width: 400px;
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 5px;
        }

        .welcome-message {
            color: #888888;
        }

        .captcha-image {
            width: 30%;
            height: auto;
        }

        .centered-button {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 20px;
        }

        .captcha-text {
            text-align: center;
            margin-top: 10px;
        }

        .captcha-link {
            color: blue;
        }

        .btn-send {
            background-color: #6c757d;
            border-color: #6c757d;
        }

        .btn-send:hover {
            background-color: #5a6268;
            border-color: #5a6268;
        }

        .btn-submit {
            margin-top: 20px;
            background-color: #007bff;
            border-color: #007bff;
        }

        .btn-submit:hover {
            background-color: #0056b3;
            border-color: #0056b3;
        }

        .return-login {
            margin-top: 20px;
            text-align: center;
            color: #888888;
        }

        .return-login a {
            color: blue;
        }
    </style>
    <script>
        function refreshcheckcode(obj) {
            obj.src = "{% url 'user:captcha_img' %}?r=" + Math.random();
        }
    </script>
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.js"></script>
    <script src="{% static 'js/forgetpwd.js' %}"></script>

</head>
<body>
    <div class="container">
        <h1 class="text-center">CET忘记密码</h1>
        <p class="welcome-message text-center">欢迎访问CET考试系统，请登录平台查看详情</p>
        {% if error_message %}
            <div class="alert alert-danger">{{ error_message }}</div>
        {% endif %}
        <form method="post" action="">
            {% csrf_token %}
            <div class="mb-3">
                <label for="account" class="form-label">请输入账号(手机号):</label>
                <input type="text" class="form-control" id="account" name="account" required>
            </div>
            <div class="mb-3">
                <div class="input-group">
                    <input type="text" name="code" class="form-control" placeholder="请输入验证码" id="pwd">
                    <button type="button" id="btn_send" class="btn btn-secondary btn-send">发送验证码</button>
                </div>
            </div>

            <input type="submit" name="" value="修改密码" class="btn btn-primary btn-submit">

        </form>
        <p class="return-login">返回登录界面，<a href="/user/stu_signin">点击这里</a></p>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

CET/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     {%load static%}
    <title>退出登录</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url('{% static "stu_signin_bj.png" %}');
            background-size: cover;
        }
        .container {
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        .text-center {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="text-center">
            <h1>您已经退出系统</h1>
            <form method="post" action="index">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">重新登录</button>
            </form>
        </div>
    </div>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

CET/templates/users/stu_signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%load static%}

    <title>学生登陆界面</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    <style>
        body {
            background-image: url('{% static "stu_signin_bj.png" %}');
            background-repeat: no-repeat;
            background-size: cover;
        }

        .container {
            margin-top: 100px;
            width: 400px;
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 5px;
        }

        .welcome-message {
            color: #888888;
        }

        .captcha-image {
            width: 30%;
            height: auto;
        }
        .centered-button {
        display: flex;
        justify-content: center;
        margin-top: 10px; /* 调整按钮的上边距，可以根据需要进行调整 */
        }
        .captcha-text {
        text-align: center;
        margin-top: 5px; /* 调整小字与验证码图片之间的上边距，可以根据需要进行调整 */
        }

        .captcha-link {
        color: blue; /* 设置小字的颜色为蓝色 */
        }
    </style>
    <script>
        function refreshcheckcode(obj){
            obj.src="{%url 'user:captcha_img'%}?r="+Math.random()
        }
    </script>
</head>
<body>
    <div class="container">
        <h1 class="text-center">CET学生登录界面</h1>
        <p class="welcome-message text-center">欢迎访问CET考试系统，请登录平台查看详情</p>
        {% if error_message %}
            <div class="alert alert-danger">{{ error_message }}</div>
        {% endif %}
        {% if success_message %}
            <div class="alert alert-success">{{ success_message }}</div>
        {% endif %}
        <form method="post" action="{% url 'user:stu_signin' %}">
            {% csrf_token %}
            <div class="mb-3">
                <label for="account" class="form-label">账号(手机号):</label>
                <input type="text" class="form-control" id="account" name="account" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">密码:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <tr>
                <td>
                    <label for="check_code" class="form-label">验证码:</label>
                </td>
                <td>
                    <div class="input-group">
                        <input type="text" class="form-control" id="check_code" name="check_code" placeholder="请输入验证码" required>
                        <img src="{% url 'user:captcha_img' %}" onclick="refreshcheckcode(this);" class="captcha-image">
                    </div>
                </td>
            </tr>
        <div class="captcha-text">
            <p class="text-center mb-0">
                <a href="#" class="captcha-link">看不清请点击验证码</a>
            </p>
        </div>
        <div class="more_input clearfix">
            <a href="{% url 'user:forget_password' %}">忘记密码</a>
        </div>
        <div class="text-center centered-button">
            <button type="submit" class="btn btn-primary">登录</button>
        </div>

        </form>
        <p class="text-center mt-3">如果没有账号，请注册：</p>
        <div class="text-center">
            <a href="/user/stu_signup" class="btn btn-success">注册账号</a>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

CET/templates/users/sucess_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册成功</title>
    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            text-align: center;
            font-family: Arial, sans-serif;
        }

        .login-link {
            text-decoration: underline;
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div>
        <h1>您已经注册成功！</h1>
        <p>
            请
            <a class="login-link" href="登录页面的URL">登录</a>
        </p>
    </div>
</body>
</html>

CET/templates/users/tea_signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {%load static%}
    <title>教师登陆界面</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    <style>
        body {
            background-image: url('{% static "tea_signin.png" %}');
            background-repeat: no-repeat;
            background-size: cover;
        }

        .container {
            margin-top: 100px;
            width: 400px;
            background-color: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 5px;
        }

        .welcome-message {
            color: #888888;
        }

        .captcha-image {
            width: 30%;
            height: auto;
        }
        .centered-button {
        display: flex;
        justify-content: center;
        margin-top: 10px; /* 调整按钮的上边距，可以根据需要进行调整 */
        }
        .captcha-text {
        text-align: center;
        margin-top: 5px; /* 调整小字与验证码图片之间的上边距，可以根据需要进行调整 */
        }

        .captcha-link {
        color: blue; /* 设置小字的颜色为蓝色 */
        }
    </style>
    <script>
        function refreshcheckcode(obj){
            obj.src="{%url 'user:captcha_img'%}?r="+Math.random()
        }
    </script>
</head>
<body>
    <div class="container">
        <h1 class="text-center">CET教师登录界面</h1>
        <p class="welcome-message text-center">欢迎访问CET考试系统，请登录平台查看详情</p>
        {% if error_message %}
            <div class="alert alert-danger">{{ error_message }}</div>
        {% endif %}
        <form method="post" action="">
            {% csrf_token %}
            <div class="mb-3">
                <label for="account" class="form-label">账号(手机号):</label>
                <input type="text" class="form-control" id="account" name="account" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">密码:</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <tr>
                <td>
                    <label for="check_code" class="form-label">验证码:</label>
                </td>
                <td>
                    <div class="input-group">
                        <input type="text" class="form-control" id="check_code" name="check_code" placeholder="请输入验证码" required>
                        <img src="{% url 'user:captcha_img' %}" onclick="refreshcheckcode(this);" class="captcha-image">
                    </div>
                </td>
            </tr>
            <div class="captcha-text">
                <p class="text-center mb-0">
                    <a href="#" class="captcha-link">看不清请点击验证码</a>
                </p>
            </div>
            <div class="more_input clearfix">
                <a href="{% url 'user:forget_password_tea' %}">忘记密码</a>
            </div>
            <div class="text-center centered-button">
                <button type="submit" class="btn btn-primary">登录</button>
            </div>


        </form>
        <p class="text-center mt-3">如果没有账号，请注册：</p>
        <div class="text-center">
            <a href="/user/tea_signup" class="btn btn-success">注册账号</a>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>